name: code-coverage

on:
  workflow_dispatch:
  push: 
     branches: [develop]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
        BRIDGE_POLARIS_SERVERURL: ${{ secrets.BRIDGE_SERVERURL }}
        BRIDGE_POLARIS_ACCESSTOKEN: ${{ secrets.BRIDGE_ACCESSTOKEN }}
        BRIDGE_POLARIS_ASSESSMENT_TYPES: 'SAST,SCA'
        BRIDGE_POLARIS_APPLICATION_NAME: ${{ github.event.repository.name }}
        BRIDGE_POLARIS_PROJECT_NAME: ${{ github.event.repository.name }}
        BRIDGE_POLARIS_BRANCH_NAME: ${{ github.event.ref_name }}
        BRIDGE_BLACKDUCK_ARGS: --detect.component.location.analysis.enabled=${{ vars.ENABLER }}
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      id: build-step
      with:
        java-version: 17
        distribution: microsoft
        cache: maven
    - name: Polaris Full Scan
      if: ${{ github.event_name != 'pull_request' }}
      run: |
         curl -fLsS -o bridge.zip ${{ vars.BRIDGECLI_LINUX64 }} && unzip -qo -d $RUNNER_TEMP bridge.zip && rm -f bridge.zip
         ls -lrt $RUNNER_TEMP
         $RUNNER_TEMP/synopsys-bridge --verbose --stage polaris > current_scan_results.json
         ls -lrt $RUNNER_TEMP
         ls -lrt ${{ github.workspace }}