name: Java CI with Maven

on:
  workflow_dispatch:
  #push: 
     #branches: [develop]   
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Create artifact
      run: | 
        cd target
        ls -lrt
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: result-artifact
        path: target/my-app-1.0-SNAPSHOT.jar
    - name: download artifact
      uses: actions/download-artifact@v4
      with:
         name: result-artifact
         path: ./target
    - name: Display structure of downloaded files
      run: ls -R target/my-app-1.0-SNAPSHOT.jar

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
