name: polaris-bridge-cli

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      BRIDGE_POLARIS_SERVERURL: ${{ secrets.BRIDGE_SERVERURL }}
      BRIDGE_POLARIS_ACCESSTOKEN: ${{ secrets.BRIDGE_ACCESSTOKEN }}
      BRIDGE_POLARIS_ASSESSMENT_TYPES: 'SAST,SCA'
      BRIDGE_POLARIS_APPLICATION_NAME: ${{ github.event.repository.name }}
      BRIDGE_POLARIS_PROJECT_NAME: ${{ github.event.repository.name }}
      BRIDGE_POLARIS_BRANCH_NAME: ${{ github.event.ref_name }}
      BRIDGE_DETECT_ARGS: '-d'

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      id: build-step
      with:
        java-version: 17
        distribution: microsoft
        cache: maven
    - name: Polaris Full Scan
      if: ${{ github.event_name != 'pull_request' }}
      run: |
         ls -lrt $RUNNER_TEMP
         curl -fLsS -o bridge.zip ${{ vars.BRIDGECLI_LINUX64 }} && unzip -qo -d $RUNNER_TEMP bridge.zip && rm -f bridge.zip
         $RUNNER_TEMP/synopsys-bridge --verbose --diagnostics --stage polaris


    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
       name: result-artifact
       path: ${{ github.workspace }}/.bridge/Polaris Blackduck Execution/detect/runs/*
      
    #- name: Upload artifact
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: result-artifact
    #    path: target/my-app-1.0-SNAPSHOT.jar
    #- name: download artifact
    #  uses: actions/download-artifact@v4
    #  with:
    #    name: result-artifact
    #    path: ./target
    #- name: Display structure of downloaded files
    #  run: ls -R target/my-app-1.0-SNAPSHOT.jar
