name: polaris-bridge-cli

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      BRIDGE_POLARIS_SERVERURL: ${{ secrets.BRIDGE_SERVERURL }}
      BRIDGE_POLARIS_ACCESSTOKEN: ${{ secrets.BRIDGE_ACCESSTOKEN }}
      BRIDGE_POLARIS_ASSESSMENT_TYPES: 'SAST,SCA'
      BRIDGE_POLARIS_APPLICATION_NAME: ${{ github.event.repository.name }}
      BRIDGE_POLARIS_PROJECT_NAME: ${{ github.event.repository.name }}
      BRIDGE_POLARIS_BRANCH_NAME: ${{ github.event.ref_name }}

    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: microsoft
        cache: maven
    - name: Polaris Full Scan
      if: ${{ github.event_name != 'pull_request' }}
      run: |
         ls -lrt $RUNNER_TEMP
         curl -fLsS -o bridge.zip ${{ vars.BRIDGECLI_LINUX64 }} && unzip -qo -d $RUNNER_TEMP bridge.zip && rm -f bridge.zip
          $RUNNER_TEMP/synopsys-bridge --verbose --stage polaris 
